steps:
  - name: "gcr.io/cloud-builders/npm"
    entrypoint: "npm"
    args: ["install"]
  - name: "gcr.io/cloud-builders/npm"
    entrypoint: "npm"
    args: ["test"]
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "gcloud"
    args: ["functions", "deploy", "--project", "haynes-boat-dev", "savePacket", "--runtime", "nodejs10", "--trigger-http"]

